### ISSUE TITLE
Manhattan encoding

### ISSUE THREAD

**Issue by flowbish** [flowbish/cs439-audio#3]
If a physical signal is held in one state too long, it can result in desynchronization between clocks of the endpoints. Manhattan encoding helps this issue by ensuring at least one transition per clock cycle, at the cost of halving the data rate. 

Manhattan encoding was added into the transmitter with commit 2e3ab7b as a compilation flag `-DMANCHESTER`.

**Comment by patrick0606** [comment]
I am pretty sure that it's called Manchester encoding rather than Manhattan, although I also sometimes make that mistake XD
Sure, I will add Manchester to my codes. It shouldn't be too hard

**Comment by flowbish** [comment]
Ah, yes, my bad! I was just doing some proofs involving Manhattan distances when I wrote this >.>

**Comment by flowbish** [comment]
Added in commit 2e3ab7b.
